baseurl = "https://holly.clibbon.com"
title = "Holly Clibbon"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "Portfolio for Holly Clibbon"
  copyright = "&copy;2022 Holly Clibbon"
  sidebarAbout = [
    "A portfolio highlighting some of the work completed during my time as an MSc AR/VR student at Goldsmiths University, London (2021/22). Click on the images in my portfolio to learn more about each project piece."
  ]
  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  linkedin      = "https://www.linkedin.com/in/hollyclibbon/"
  github        = "https://github.com/vendorofdoom/"
  itch          = "https://vendorofdoom.itch.io/"
